export const emojiMap = {
  "Burdock": "🌿",
  "Catnip": "🌱",
  "Dandelion": "🌼",
  "Echinacea": "💜",
  "Elderberry": "🫐",
  "Goldenrod": "🌾",
  "Motherwort": "🌸",
  "Mullein": "🌿",
  "Stinging Nettle": "🌿",
  "Yellow Dock": "🌱",
  "Chaga": "🍄",
  "Morel": "🍄",
  "Maitake": "🍄",
  "Lion's Mane": "🍄",
  "Oyster Mushroom": "🍄",
  "Cauliflower Mushroom": "🍄",
  "Chicken of the Woods": "🍄",
  "Chanterelle": "🍄",
  "Giant Puffball": "🍄",
  "Turkey Tail": "🍄",
};